# Generated by Django 2.2.17 on 2021-05-11 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopt_animals', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt_animals.Post', verbose_name='MessageRoom Post')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('message_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt_animals.MessageRoom', verbose_name='Message')),
            ],
        ),
    ]
