# Generated by Django 2.2.17 on 2021-06-04 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopt_animals', '0005_message_messageroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='message_user'),
            preserve_default=False,
        ),
    ]
