# Generated by Django 2.2.17 on 2021-06-04 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_animals', '0006_message_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
