# Generated by Django 2.2.17 on 2021-06-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_animals', '0007_message_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
